# Generated by Django 4.0.7 on 2023-03-09 01:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postcomments",
            old_name="comment",
            new_name="comment_user",
        ),
    ]
