# Generated by Django 4.1.7 on 2023-03-10 14:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BondRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[("friend", "Friend"), ("follower", "Follower")],
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(auto_now=True)),
                ("aproved", models.BooleanField(blank=True, null=True)),
                ("is_active", models.BooleanField(blank=True, default=True)),
            ],
        ),
    ]
