# Generated by Django 4.1.7 on 2023-03-08 17:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("requests", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bondrequest",
            name="is_active",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="bondrequest",
            name="aproved",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="bondrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("friend", "Friend"),
                    ("follower", "Follower"),
                    ("cancel", "Cancel"),
                ],
                max_length=20,
            ),
        ),
    ]
